services:
  - type: web
    name: doctor-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.16
      - key: DATABASE_URL
        fromDatabase:
          name: doctor-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: USER_PASSWORD
        sync: false

databases:
  - name: doctor-db
    databaseName: doctors
    user: doctors_user
    plan: free
